spring:
    application:
        name: auth
    cloud:
        vault:
            host: localhost
            port: 8200 
            scheme: http 
            token: 
    datasource:
        url: jdbc:postgresql://localhost:54320/mydatabase
        username: myuser
        password: mypassword
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    data:
        redis: # Cấu hình Redis
            host: localhost # Địa chỉ của Redis server
            port: 6379 # Port của Redis server
            password: # Mật khẩu (nếu có)
            database: 0 # Chọn database (mặc định là 0)
            timeout: 2000 # Timeout cho các operation (ms)
